baseURL = 'https://wolfiii.gay'
languageCode = 'DE-de'
title = 'Wolfiii'
theme = 'coming-soon'

[params]
    title = "Wolfiii"
    favicon = ""
    message = "COMING SOON!" 
    release = "Jan 1, 2025" 
    background = "" 